version: '3.8'

services:
  mysql:
    image: mysql:9.0
    container_name: account_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: account_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: